server:
  port: 8081

spring:
  application:
    name: employee-command-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      spring.json.add.type.headers: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic: employee.events